// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZpymeye6fXOt3789x5OSi66TXer_bSo',
    appId: '1:401522117542:web:b3c884169bc7ea54e39d67',
    messagingSenderId: '401522117542',
    projectId: 'staff-cleaner-34fc2',
    authDomain: 'staff-cleaner-34fc2.firebaseapp.com',
    storageBucket: 'staff-cleaner-34fc2.appspot.com',
    measurementId: 'G-2LJXHWWZHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr9vYxKAe80uOOmDqp1H4Cxo35bPjMcOw',
    appId: '1:401522117542:android:705ba722bc23a87fe39d67',
    messagingSenderId: '401522117542',
    projectId: 'staff-cleaner-34fc2',
    storageBucket: 'staff-cleaner-34fc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComkXiZU2GAyws9Ff93DHa5Qc-bVjhDls',
    appId: '1:401522117542:ios:6c31f1b28083539be39d67',
    messagingSenderId: '401522117542',
    projectId: 'staff-cleaner-34fc2',
    storageBucket: 'staff-cleaner-34fc2.appspot.com',
    iosBundleId: 'com.example.staffCleaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComkXiZU2GAyws9Ff93DHa5Qc-bVjhDls',
    appId: '1:401522117542:ios:6c31f1b28083539be39d67',
    messagingSenderId: '401522117542',
    projectId: 'staff-cleaner-34fc2',
    storageBucket: 'staff-cleaner-34fc2.appspot.com',
    iosBundleId: 'com.example.staffCleaner',
  );
}
