class Food {
  String name;
  String image;
  String desc;
  String category;
  bool isNew;
  double rate;
  int reviews;
  int time;
  int portion;
  String chefName;
  String chefPhoto;
  String chefAddress;
  List<String> ingredients;
  List<String> procedures;

  Food({
    required this.name,
    required this.image,
    required this.desc,
    required this.category,
    required this.isNew,
    required this.rate,
    required this.reviews,
    required this.time,
    required this.portion,
    required this.chefName,
    required this.chefPhoto,
    required this.chefAddress,
    required this.ingredients,
    required this.procedures,
  });
}

List<Food> listFood = [
  Food(
    name: 'Es Cincau Gula Aren',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126894/assets-smartchef/food/2215740095_azztbq.jpg',
    desc:
        'Resep es cincau menduduki peringkat teratas dalam menu takjil jenis es yang kerap dicari di bulan Ramadan, bersaing ketat dengan es buah dan es kolak. Cara membuatnya sangat mudah dan praktis, sehingga bisa kamu siapkan di beberapa menit menjelang azan magrib.\n\nAda dua jenis cincau yang bisa kamu pilih untuk membuat minuman segar ini, yaitu cincau hitam dan cincau hijau. Keduanya sama-sama enak dan menyegarkan, tapi kali ini, Masak Apa Hari Ini memilih menggunakan cincau hitam. Tentu bukan tanpa alasan kami memilih jenis cincau ini. Diketahui, cincau hitam mengandung serat larut yang tinggi, sehingga dapat membantu memperlancar pencernaan. Pas banget buat kamu yang kurang asupan sayur dan buah selama bulan puasa.\n\nYuk, segera siapkan bahan-bahan untuk membuat resep es cincau gula aren ini, supaya kamu bisa sat set ketika membuatnya.',
    category: 'Dessert',
    isNew: false,
    rate: 4.9,
    reviews: 394,
    time: 30,
    portion: 4,
    chefName: 'Chef Arnold',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/dQ6BDGovwq_zwpby6.jpg',
    chefAddress: 'Surabaya, Indonesia',
    ingredients: [
      '600_ml susu cair',
      '400_ml air panas',
      '200_g cincau hitam, potong kotak kecil',
      '4_kantung SariWangi Teh Asli ',
      '6_sdm gula aren',
      '_Es batu',
    ],
    procedures: [
      '1._Seduh SariWangi Teh Asli bersama air panas dan gula aren sambil diaduk hingga gula larut. Diamkan selama 3 menit agar warna teh pekat.',
      '2._Aduk rata bersama susu cair.',
      '3._Siapkan gelas saji yang sudah diisi dengan es batu dan cincau. Tuang campuran SariWangi Teh Asli dan susu ke dalamnya. Sajikan.',
    ],
  ),
  Food(
    name: 'Iga Bakar',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126677/assets-smartchef/food/6835291847_tryuoq.jpg',
    desc:
        'Penyuka masakan serba iga wajib banget cobain resep iga bakar empuk ini! Rasanya mirip seperti iga bakar yang disajikan di restoran. Supaya daging iga empuk, kamu bisa memasak daging iga dalam panci presto ataupun slow cooker.\n\nUntuk pilihan daging iga, kamu bisa menggunakan daging iga short ribs atau juga bagian back ribs yang bikin sensasi makan iga lebih puas. Bagian back ribs merupakan bagian iga yang biasa digunakan untuk konro, yaitu bertulang panjang dengan lapisan daging yang tebal.\n\nUntuk melengkapi resep iga bakar ini, sajikan bersama sambal kesukaan kamu, misalnya sambal goang, sambal tomat, atau sambal terasi pedas yang biasa dijajakan pedagang pecel lele.\n\nSelain resep iga bakar empuk ini, coba juga ide masakan daging iga lainnya seperti sop iga, gulai iga sapi, rawon iga, hingga mie kuah iga. Ikuti juga akun instagram Masak Apa Hari Ini buat kamu yang nggak mau ketinggalan resep-resep menarik lainnya.',
    category: 'Daging',
    isNew: false,
    rate: 4.8,
    reviews: 78,
    time: 120,
    portion: 4,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '1500_g iga sapi',
      '1500_ml air',
      '3_lembar daun salam',
      '3_cm lengkuas, memarkan',
      '4_butir cengkih',
      '6_lembar daun jeruk',
      '100_ml Bango Kecap Manis',
      '3_sdm Royco Saus Tiram',
      '4_sdm minyak, untuk menumis Margarin, untuk olesan',
      '10_butir bawang merah',
      '5_siung bawang putih',
      '5_butir kemiri',
      '3_buah cabai merah besar',
      '1_cm jahe',
      '½_sdm garam',
      '½_sdm pala bubuk',
      '½_sdm merica putih bubuk',
    ],
    procedures: [
      '1._Rebus iga dalam panci presto bersama daun salam, lengkuas, dan cengkih hingga empuk. Bila tidak menggunakan panci presto, rebus iga bersama 3 liter air hingga mendidih, kemudian kecilkan api dan tutup panci. Masak hingga empuk. Angkat dan sisihkan daging iga.',
      '2._Panaskan minyak, tumis bumbu halus, dan daun jeruk hingga harum.',
      '3._Masukkan iga sapi, aduk hingga rata. Tambahkan Bango Kecap Manis, Royco Saus Tiram, dan 250 ml air kaldu sisa merebus iga.',
      '4._Tutup wajan dan kecilkan api. Masak hingga bumbu meresap. Angkat. Diamkan selama 1 jam atau lebih agar bumbu lebih meresap ke dalam iga.',
      '5._Panaskan grill pan sambil diolesi dengan margarin. Masak iga sambil diolesi sisa bumbu tumis dan margarin hingga merata dan permukaannya sedikit mengering. Angkat.',
      '6._Sajikan bersama lalapan sayuran dan sambal.',
    ],
  ),
  Food(
    name: 'Seblak Kuah Pedas',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126816/assets-smartchef/food/9203648392_e7c5ka.jpg',
    desc:
        'Indonesia yang kaya rempah terkenal akan masakannya yang pedas-pedas. Jika membandingkan dengan negara sekitar, masakan khas Indonesia punya rasa pedas yang lebih berempah dan tak kalah nendang. Mungkin salah satu saingannya dalam hal makanan pedas adalah Thailand, yang terkenal dengan cita rasa asam pedasnya. Nah, resep seblak kuah pedas ini bolehlah jadi tandingannya.\n\nGenerasi millennial memang serba kreatif dalam menciptakan makanan baru, meskipun entah sampai kapan sebetulnya akan bertahan. Mungkin generasi berikutnya yang akan jadi saksi kalau apa yang diciptakan generasi sekarang ini akan bertahan di kancah perkulineran Indonesia sampai puluhan tahun ke depan.',
    category: 'Sayuran',
    isNew: false,
    rate: 4.8,
    reviews: 163,
    time: 40,
    portion: 1,
    chefName: 'Chef Arnold',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/dQ6BDGovwq_zwpby6.jpg',
    chefAddress: 'Surabaya, Indonesia',
    ingredients: [
      '100_g kerupuk merah mentah',
      '5_buah bakso sapi, iris',
      '2_buah sosis sapi, iris',
      '1_butir telur ',
      '100_g sawi putih, iris',
      '1_sdm Bango Kecap Manis Pedas',
      '_Garam',
      '_Air',
      '_Minyak',
      '1_siung bawang putih ',
      '5_buah bawang merah ',
      '8_buah cabai rawit merah ',
      '1_cm kencur',
      '_Bawang merah goreng',
      '_Daun bawang, iris',
    ],
    procedures: [
      '1._Cuci bersih kerupuk. Rebus air hingga mendidih, kemudian rendam kerupuk kurang lebih 15 menit.',
      '2._Panaskan minyak dan wajan. Tumis bumbu halus hingga harum dan masukkan telur, bakso, sosis dan sawi putih. Aduk hingga sayuran sedikit layu.',
      '3._Masukan kerupuk yang sudah direndam dengan air, tambahkan garam dan gula secukupnya.',
      '4._Tambahkan air sedikit kemudian beri Bango Kecap Manis Pedas Gurih. Masak hingga air mengental.',
      '5._Sajikan dengan ditaburi daun bawang dan bawang merah goreng.',
    ],
  ),
  Food(
    name: 'Dimsum Ayam Udang',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126721/assets-smartchef/food/1938503506_qyd9ez.jpg',
    desc:
        'Lagi cari ide frozen food untuk stok camilan? Daripada beli, mending coba resep dimsum ayam udang ini, yuk! Gunakan potongan daging dari bagian paha ayam sehingga menghasilkan tekstur daging yang kenyal sekaligus lebih gurih. Untuk pilihan sayurnya, selain jamur hioko, kamu bisa menggunakan wortel, zucchini, atau jenis jamur lainnya seperti jamur kancing, jamur kuping, atau jamur tiram.\n\nLabu parut siam ditambahkan supaya adonan dimsum atau siomay ayam lebih kokoh sekaligus menambahkan tekstur kenyal sekaligus empuk. Agar adonan siomay ayam udang ini lebih sedap, tambahkan Royco Saus Tiram dan Royco Kaldu Ayam.\n\nKalau ingin dijadikan stok frozen food, siapkan bahan resep dimsum ayam udang ini sekaligus banyak dan bekukan dalam freezer. Susun dalam wadah tertutup dan bila ingin ditumpuk, lapisi dengan baking paper supaya tidak menempel. Coba juga ide resep frozen food lainnya seperti egg chicken roll, kaki naga, dan lumpia goreng.',
    category: 'Ayam',
    isNew: false,
    rate: 4.6,
    reviews: 118,
    time: 120,
    portion: 5,
    chefName: 'Chef Juna',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/718h2ja82k_qgzrna.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '400_g filet paha ayam tanpa kulit, potong-potong',
      '150_g udang kupas, cincang',
      '100_g tepung sagu',
      '100_g jamur hioko, cincang',
      '100_g labu siam kupas, parut',
      '20_lembar kulit dimsum',
      '1_batang daun bawang, iris halus',
      '2_sdm minyak wijen',
      '2_putih telur',
      '4_siung bawang putih, haluskan',
      '2_sdm Royco Saus Tiram',
      '½_sdm Royco Kaldu Ayam',
      '1_sdt garam',
      '½_sdt merica putih bubuk',
      '4_sdm wortel parut',
      '8_buah cabai rawit merah, rebus',
      '6_siung bawang putih, rebus',
      '6_sdm Jawara Saus Sambal Extra Hot',
      '1_sdt gula pasir',
      '1_sdt Royco Kaldu Ayam',
      '½_sdm tepung maizena, larutkan dengan 2 sdm air',
      '1_sdm cuka',
      '200_ml air',
    ],
    procedures: [
      '1._Masukkan daging ayam, putih telur, minyak wijen, Royco Saus Tiram, Royco Kaldu Ayam, garam, dan merica ke dalam food processor. Proses hingga tercampur rata.',
      '2._Pindahkan ke dalam wadah. Tambahkan udang, tepung sagu, jamur, labu siam, dan daun bawang, aduk rata.',
      '3._Ambil selembar kulit dimsum, letakkan 1 sdm penuh adonan dimsum ke atasnya. Rapikan kulit hingga membentuk siomay. Sisihkan. Ulangi proses serupa pada sisa adonan hingga habis. Beri wortel parut ke atas dimsum untuk hiasan.',
      '4._Panaskan dandang, kukus dimsum ayam udang hingga habis. Angkat. Sisihkan.',
      '5._Saus dimsum: Haluskan cabai dan bawang putih. Masukkan ke dalam panci kecil. Tuang air, Jawara Saus Sambal Extra Hot, gula pasir, dan Royco Kaldu Ayam. Panaskan di atas api kecil hingga hampir mendidih. Tambahkan larutan maizena, aduk hingga mengental. Angkat dan tambahkan cuka, aduk rata. Sisihkan.',
      '6._Sajikan dimsum bersama sausnya.',
    ],
  ),
  Food(
    name: 'Lumpia Vietnam Sayuran',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695132646/assets-smartchef/food/417440626_jj6gnx.jpg',
    desc:
        'Goi cuon lebih familiar dikenal dengan nama summer rolls atau lumpia Vietnam. Tersaji apik dalam balutan kulit transparan yang terbuat dari beras. Isiannya pun bermacam-macam, mulai dari sayuran mentah, bihun tawar, selada, timun, wortel, serta ketumbar. Perpaduan bahannya membuat cemilan yang satu ini terasa aromatik dan menyegarkan mulut.\n\nAgar semakin lezat, sajikan lumpia Vietnam dengan saus yang terbuat dari adonan kecap asin, air jeruk nipis, gula pasir, cabe rawit, dan ketumbar. Tak lupa tambahkan Royco Kaldu Jamur sebagai pelengkap dimensi rasa saus lumpia. Rendah kalori dan aman dimakan kapan saja, tak heran jika lumpia Vietnam menjadi salah satu cemilan yang digadang-gadang oleh penggiat gaya hidup sehat di luar sana.\n\nPenasaran cara membuatnya? Yuk, daripada menunggu lama, langsung saja cek resepnya!',
    category: 'Sayuran',
    isNew: true,
    rate: 4.8,
    reviews: 138,
    time: 30,
    portion: 4,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '16_lembar banh trang atau rice paper Vietnam',
      '1_buah mentimun, potong bentuk korek api 3 cm',
      '150_g selada iceberg',
      '100_g bihun, rendam air panas hingga lunak, tiriskan',
      '100_g wortel, potong bentuk korek api 3 cm',
      '12_tangkai daun ketumbar, potong 4 cm',
      '100_ml air',
      '2_sdm kecap ikan',
      '2_sdm air jeruk nipis',
      '1.5_sdm gula pasir',
      '1_sdt Royco Kaldu Jamur',
      '8_buah cabai rawit merah, cincang halus',
      '2_sdm daun ketumbar cincang',
    ],
    procedures: [
      '1._Siapkan wadah lebar dengan diameter melebihi rice paper. Isi dengan air cukup untuk merendam. Rendam rice paper secara bertahap dalam air dingin selama 30 detik atau hingga lentur dan bening.',
      '2._Ambil selembar rice paper, tiriskan. Isi dengan daun selada, bihun, mentimun, dan wortel. Beri daun ketumbar ke atasnya. Gulung rapi. Ulangi proses serupa pada sisa bahan. SIsihkan.',
      '3._Saus: Aduk air, kecap ikan, gula pasir, dan Royco Kaldu Jamur hingga larut. Masukkan cabai rawit dan daun ketumbar, aduk. ',
      '4._Sajikan Lumpia Vietnam dengan sausnya.',
    ],
  ),
  Food(
    name: 'Ayam Goreng Korea',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126763/assets-smartchef/food/1728349273_tlm618.jpg',
    desc:
        'Salah satu makanan yang paling sering disorot di drama Korea Selatan adalah ayam goreng Korea. Setuju, kan? Umumnya hidangan ayam goreng tepung ini terlihat dinikmati sebagai menu praktis di malam hari sambil bersantai. Nah, pas banget buat kamu yang lagi pengen maraton drama Korea Selatan sambil makan, yuk, bikin ayam goreng pedas manis ini!\n\nAda beberapa versi lapisan tepung untuk ayam goreng berlapis saus gochujang ini. Diantaranya adalah dengan tepung kentang-tepung terigu atau tepung maizena.\n\nJadi kamu bisa menggunakan alternatif tepung maizena bila tak punya tepung kentang di rumah. Kalau menggunakan tepung maizena, cukup lumuri sesudah daging ayam dimarinasi. Bedanya kalau menggunakan tepung maizena hasil lapisan tepungnya lebih tipis. Cocok buat kamu yang nggak suka dengan ayam goreng berlapis tepung tebal atau banyak.\n\nSajikan ayam goreng Korea ini bersama jjajangmyeon, kimbab, rabokki, atau pajeon supaya nonton drakor makin seru.',
    category: 'Ayam',
    isNew: true,
    rate: 4.9,
    reviews: 235,
    time: 60,
    portion: 4,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '1_kg sayap ayam, potong 2 bagian',
      '1_sdm wijen sangrai',
      '_Minyak, untuk menggoreng',
      '100_g tepung kentang',
      '60_g tepung terigu',
      '100_ml susu cair',
      '1_sdt Royco Kaldu Ayam',
      '1_sdt garam',
      '1_sdt cuka',
      '½_sdt merica hitam bubuk',
      '½_sdt baking soda',
      '1_butir telur',
      '3_siung bawang putih, cincang halus',
      '5_sdm gochujang',
      '5_sdm Jawara Saus Sambal Extra Hot',
      '4_sdm corn syrup atau madu',
      '½_sdm cuka',
      '1_sdm minyak, untuk menumis',
    ],
    procedures: [
      '1._Lumuri daging ayam dengan bumbu marinasi hingga merata.',
      '2._Tambahkan seperempat bagian adonan tepung. Aduk rata sambil diremas. Marinasi selama 1 jam dalam kulkas atau lebih agar bumbu lebih meresap.',
      '3._Keluarkan sayap ayam, lumuri daging ayam dengan sisa adonan tepung.',
      '4._Panaskan wajan, tuang minyak. Biarkan hingga minyak panas, goreng sayap ayam hingga matang. Angkat dan tiriskan. Diamkan hingga tidak panas. Sisihkan.',
      '5._Saus: Panaskan minyak, tumis bawang putih hingga harum. Masukkan semua sisa bahan termasuk Jawara Saus Sambal Extra Hot, aduk rata. Angkat. Sisihkan.',
      '6._Panaskan kembali minyak di atas api besar, goreng kembali sayap ayam hingga permukaannya garing. Angkat dan sisihkan.',
      '7._Panaskan kembali saus, aduk rata bersama sayap ayam. Angkat dan taburi dengan wijen sangrai, aduk. Sajikan.',
    ],
  ),
  Food(
    name: 'Ayam Rica-Rica Kemangi',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695132053/assets-smartchef/food/8274635267_rmnzpi.jpg',
    desc:
        'Sebagai bahan dalam resep ayam rica-rica kemangi khas Manado, daun kemangi punya peran utama untuk memperkuat aroma dan menonjolkan keunikan dari hidangan ini. Tapi tak hanya untuk resep ini, lho, karena rupanya kemangi juga kerap dipakai dalam banyak masakan lainnya. Dari lalapan sederhana hingga untuk menginfusi aroma pada bumbu halus atau masakan yang tengah dimasak, ternyata kehadiran kemangi hampir selalu ada!\n\nBicara soal jenisnya, kemangi dikategorikan sebagai herba atau tumbuhan terna yang memiliki tangkai rawan. Termasuk di antaranya adalah ketumbar dan juga peterseli. Kemudian ada juga tumbuhan terna yang memiliki tangkai lebih keras seperti oregano, thyme, ataupun rosemary.',
    category: 'Ayam',
    isNew: false,
    rate: 4.7,
    reviews: 153,
    time: 60,
    portion: 4,
    chefName: 'Chef Arnold',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/dQ6BDGovwq_zwpby6.jpg',
    chefAddress: 'Surabaya, Indonesia',
    ingredients: [
      '1_ekor ayam kampung, potong 8 bagian, buang kulitnya',
      '150_g terung, belah 2 bagian, potong 3 bagian',
      '1_buah jeruk nipis, ambil airnya',
      '1_sdt garam',
      '6_lembar daun jeruk, buang tulang daun',
      '3_batang serai, memarkan',
      '200_ml air',
      '1_sdm Bango Kecap Manis Hitam Gurih',
      '1_sdt Royco Kaldu Ayam',
      '100_g kemangi, petiki daunnya',
      '3_sdm minyak, untuk menumis',
      '12_buah cabai rawit',
      '4_buah cabai merah besar',
      '10_butir bawang merah',
      '6_siung bawang putih',
      '3_cm jahe',
      '2_cm kunyit',
      '1_sdt garam',
    ],
    procedures: [
      '1._Lumuri daging ayam dengan air jeruk nipis dan garam. Sisihkan.',
      '2._Panaskan minyak, tumis bumbu halus bersama daun jeruk dan serai hingga harum.',
      '3._Masukkan daging ayam, aduk rata. Tambahkan air, Bango Kecap Manis Hitam Gurih, dan Royco Kaldu Ayam. Masak hingga setengah matang.',
      '4._Tambahkan terong, aduk. Tutup wajan, masak hingga matang dan airnya menyusut.',
      '5._Tambahkan daun kemangi, aduk hingga layu. Angkat dan sajikan.',
    ],
  ),
  Food(
    name: 'Sate Cumi Bakar',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695133316/assets-smartchef/food/8290374839_zonclq.jpg',
    desc:
        'Sedang kehabisan ide memasak cumi? Mungkin kamu bosan dengan olahan cumi yang itu-itu saja seperti cumi saus asam manis, cumi goreng tepung, cumi balado, atau cumi masak saus padang. Kali ini tak ada salahnya menghadirkan sensasi makan di restoran seafood tepi pantai dengan mencoba resep Sate Cumi Bakar Bumbu Pedas.\n\nUnik, resep Sate Cumi Bakar Bumbu Pedas ini dimarinasi dengan pedas gurih Jawara Saus Sambal Extra Hot kemudian disajikan dengan Jawara Cabai Tabur Bawang Goreng. Dengan sensasi bawang goreng di dalam kedua olahan cabai ini, tentu sate cumi jadi lebih unik dan mantap.',
    category: 'Seafood',
    isNew: false,
    rate: 4.8,
    reviews: 132,
    time: 60,
    portion: 4,
    chefName: 'Chef Juna',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/718h2ja82k_qgzrna.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '500_g cumi segar',
      '1_sdm minyak, untuk mengoles',
      '_Tusuk satai, rendam air dingin',
      '4_sdm Jawara Saus Sambal Extra Hot',
      '3_siung bawang putih, haluskan',
      '1_cm jahe, haluskan',
      '1_sdm Bango Kecap Manis',
      '1_sdm minyak wijen',
      '1_sdm air jeruk nipis',
      '1_sdt garam',
      '½_sdt gula pasir',
      '_Jawara Cabai Tabur Bawang Goreng',
    ],
    procedures: [
      '1._Siangi cumi, buang tintanya. Kerat bagian atas badan cumi menjadi 4 bagian.',
      '2._Lumuri cumi dengan semua bahan bumbu perendam termasuk Jawara Saus Sambal Extra Hot. Sematkan bagian kepala dan badan cumi dengan tusuk satai. Diamkan dalam kulkas selama 30 menit.',
      '3._Panaskan grill pan, olesi dengan minyak. Panggang cumi hingga matang di kedua sisinya. Angkat. Sajikan dengan Jawara Cabai Tabur Bawang Goreng.',
    ],
  ),
  Food(
    name: 'Gulai Nangka Sederhana',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695132403/assets-smartchef/food/1728362798_fgl2pc.jpg',
    desc:
        'Mungkin banyak dari kalian yang penasaran dengan lezatnya resep gulai nangka muda a la masakan Padang. Tidak heran, karena masakan yang satu ini adalah menu pelengkap paling pas untuk menemani santap rendang ataupun ayam pop di restoran. Cara membuatnya juga cukup sederhana, kok. Pasti kamu bisa membuatnya sendiri di rumah!\n\nBukan hanya enak diolah sebagai sayur untuk pendamping nasi, resep ini juga pas buat kamu yang sedang mencari teman makan ketupat atau lontong. Pilih nangka muda sebagai bahan utama. Alasannya adalah karena nangka muda lebih enak dan lebih empuk. Nangka yang masih muda ditandai dengan bijinya yang tidak keras.',
    category: 'Sayuran',
    isNew: false,
    rate: 4.6,
    reviews: 83,
    time: 60,
    portion: 4,
    chefName: 'Chef Arnold',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/dQ6BDGovwq_zwpby6.jpg',
    chefAddress: 'Surabaya, Indonesia',
    ingredients: [
      '600_g nangka muda, potong-potong',
      '300_g udang kupas, sisakan ekor',
      '4_cm kunyit',
      '3_L air, untuk merebus',
      '2_sdt kari bubuk',
      '6_lembar daun jeruk',
      '3_batang serai, memarkan',
      '2_lembar daun salam',
      '800_ml susu cair rendah lemak',
      '250_ml santan kental',
      '1_sdm Royco Kaldu Ayam',
      '12_butir bawang merah',
      '5_buah cabai merah',
      '4_siung bawang putih',
      '2_cm jahe',
      '2_cm kunyit',
      '1_cm lengkuas',
      '1_sdt garam',
    ],
    procedures: [
      '1._Rebus nangka dan kunyit selama sekitar 5 menit untuk menghilangkan getahnya. Angkat. Keluarkan nangka. Sisihkan.',
      '2._Panaskan minyak, tumis bumbu halus, bubuk kari, daun jeruk, serai, dan daun salam hingga harum. Tambahkan nangka, aduk.',
      '3._Tuang susu cair, aduk. Masak hingga nangka empuk. Tuang santan, Royco Kaldu Ayam, dan udang. Masak hingga udang matang. Angkat. Sajikan.',
    ],
  ),
  Food(
    name: 'Beef Katsu',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126529/assets-smartchef/food/2194034587_ptkynw.jpg',
    desc:
        'Bicara soal hidangan katsu khas Jepang, mana yang jadi kesukaan kamu? Versi daging sapi atau daging ayam? Ada beberapa versi menyajikan daging berbalut tepung roti yang digoreng ini. Disajikan dengan saus katsu dan ada pula yang menyajikannya dengan saus katsu berwarna gelap dan kental.\n\nDiracik dari kecap inggris, Royco Saus Tiram, saus tomat, dan gula pasir, jenis saus ini gampang banget bikinnya. Agar lapisan tepung dan telur lebih menempel pada daging, diamkan daging yang sudah dilapisi tepung dalam kulkas selama 1 jam. Setelah matang, tiriskan daging selama beberapa menit, kemudian potong-potong sebelum disajikan.\n\nFungsinya supaya sari daging atau juice tidak keluar bersamaan ketika dipotong. Sehingga rasa dan tekstur daging jadi lebih sedap dan juicy. Yuk, bikin beef katsu a la restoran Jepang ini di rumah!',
    category: 'Daging',
    isNew: false,
    rate: 4.9,
    reviews: 261,
    time: 60,
    portion: 4,
    chefName: 'Chef Juna',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/718h2ja82k_qgzrna.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '½_sdt garam',
      '4_potong (@150-180 g) daging sapi has dalam',
      '¼_sdt merica hitam bubuk',
      '_Minyak, untuk menggoreng',
      '2_sdm sdm bawang bombay cincang',
      '1_siung bawang putih, cincang halus',
      '5_sdm saus tomat',
      '4_sdm kecap inggris',
      '3_sdm Royco Saus Tiram',
      '1_sdm gula pasir',
      '5_sdm air',
      '1_sdm minyak, untuk menumis',
      '2_sdm tepung terigu',
      '1_butir telur, kocok lepas',
      '6_sdm tepung panko atau tepung roti kasar',
      '100_g kol, iris halus',
      '2_buah mentimun, potong serong',
      '2_buah tomat, belah 4 bagian',
    ],
    procedures: [
      "1._Pukul-pukul daging atau tusukkan dengan garpu untuk merusak seratnya. Lumuri daging sapi dengan garam dan merica hitam bubuk. Sisihkan.",
      "2._Saus: Panaskan minyak, tumis bawang bombay dan bawang putih hingga harum. Masukkan sisa semua bahan termasuk Royco Saus Tiram, aduk hingga mendidih. Angkat. Sisihkan. Lumuri setiap potongan daging dengan tepung terigu, balur ke dalam telur, lapisi kembali dengan tepung panko hingga merata.",
      "3._Diamkan selama 1 jam dalam kulkas supaya telur dapat mengikat kedua lapisan tepung.",
      "4._Panaskan minyak, goreng daging selama 5-6 menit atau hingga matang. Angkat. Potong 5-6 bagian.",
      "5._Siapkan piring saji yang sudah diberi sayuran pelengkap. Tata beef katsu di sebelahnya. Sajikan bersama sausnya.",
    ],
  ),
  Food(
    name: 'Udang Asam Manis Pedas',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126854/assets-smartchef/food/2210987993_sjftiv.jpg',
    desc:
        'Pecinta seafood apalagi udang wajib banget cobain resep udang asam manis pedas ini di rumah. Kombinasi asam, manis, dan pedas dari tomat segar dengan tambahan Bango Kecap Manis dan Royco Saus Tiram yang bikin rasa masakan rumah seperti di restoran.\n\nUntuk rasa terbaik, pilih udang segar berukuran sedang karena dagingnya lebih tebal dan rasanya manis. Pilih udang segar ditandai dengan kepala yang masih melekat dengan badannya. Kemudian kulitnya juga terasa keras dan menempel pada badan. Saat kulit udang ditekan terasa kenyal dan tidak lembek.\n\nYuk, segera praktikkan resep udang asam manis pedas yang rasanya seperti masakan restoran ini! Coba juga resep udang goreng tepung, udang saus padang, dan tomyam udang.',
    category: 'Seafood',
    isNew: true,
    rate: 4.9,
    reviews: 97,
    time: 60,
    portion: 4,
    chefName: 'Chef Juna',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/718h2ja82k_qgzrna.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '500_g udang, buang kepala, belah punggung tidak putus',
      '3_buah tomat, iris tipis',
      '2_batang daun bawang, potong serong',
      '1_sdm air jeruk nipis',
      '4_siung bawang putih, memarkan',
      '1_buah bawang bombay, cincang halus',
      '2_cm jahe, memarkan',
      '6_buah cabai rawit merah, potong serong',
      '5_sdm air',
      '3_sdm Jawara Saus Sambal Extra Hot',
      '2_sdm Royco Saus Tiram',
      '1_sdm Bango Kecap Manis',
      '½_sdt garam',
      '3_sdm minyak, untuk menumis',
    ],
    procedures: [
      '1._Lumuri udang dengan jeruk nipis hingga merata. Sisihkan.',
      '2._Panaskan minyak. Tumis bawang putih, bawang bombay, jahe, dan cabai hingga harum.',
      '3._Masukkan tomat, kecilkan api. Tambahkan air, aduuk. Masak hingga tomat hancur.',
      '4._Tambahkan Jawara Saus Sambal Extra Hot, Royco Saus Tiram, Bango Kecap Manis, dan garam. Aduk hingga tercampur rata.',
      '5._Masukkan udang, masak di atas api sedang, aduk rata.',
      '6._Tambahkan daun bawang, aduk sebentar hingga udang matang. Angkat dan sajikan.',
    ],
  ),
  Food(
    name: 'Brown Sugar Milk Tea',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695133907/assets-smartchef/food/1201928372_itfxnp.jpg',
    desc:
        'Kalau sedang bertandang ke gerai milk tea yang ternama asal ibukota, biasanya kamu melihat kehadiran susu bubuk yang ditambahkan pada teh yang sudah diseduh sebelumnya. Lantas bagaimana dengan susu cair di resep ini? Apakah prosesnya juga dicampur dalam teh? Lalu bagaimana dengan cara menambahkan brown sugar-nya?\n\nProsesnya bisa semudah dengan mencairkan brown sugar bersama susu dengan merebusnya di atas api kecil. Matikan api setelah bercampur lalu seduh dengan kantung teh selama 5 menit dan jadilah brown sugar milk tea. Proses ini lebih praktis untuk level rumahan yang tidak selalu membuat minuman ini setiap hari. Selebihnya, kamu bisa menambahkan madu, es batu, dan cincau untuk menikmati minuman yang menyegarkan ini. Kapan-kapan kamu bahkan bisa menggantikan cincau dengan boba ataupun jenis topping kesukaan kamu lainnya. Selamat mencoba!',
    category: 'Dessert',
    isNew: false,
    rate: 4.9,
    reviews: 314,
    time: 30,
    portion: 4,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '800_ml susu cair rendah lemak',
      '4_kantung SariWangi Teh Asli ',
      '100_g cincau hitam, potong kotak kecil',
      '2_sdm brown sugar',
      '4_sdm madu',
      '_Es batu',
    ],
    procedures: [
      '1._Panaskan susu dan brown sugar di atas api kecil. Angkat.',
      '2._Seduh SariWangi Teh Asli bersama susu panas selama 5 menit. Keluarkan teh, masukkan madu, aduk rata. Sisihkan.',
      '3._Siapkan gelas saji, isi dengan es batu. Masukkan cincau. Tuang teh susu. Sajikan.',
    ],
  ),
  Food(
    name: 'Cumi Saus Tiram',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695133009/assets-smartchef/food/8392836473_m5z5lk.jpg',
    desc:
        'Yang namanya seafood, bisa jadi ada di antara kita yang masih ragu mengolahnya di rumah. Padahal Indonesia diberkahi hasil laut yang melimpah dan cumi adalah salah satunya. Mencari yang segar juga tidak sulit, lho, sebetulnya. Kamu bisa melihatnya dari tekstur cumi yang masih kenyal, kulitnya yang putih segar dengan bintik-bintik merahnya yang khas, serta baunya yang tidak menyengat. Jangan ragu untuk berdiskusi dengan penjual mengenai kesegarannya. Bahkan berbelanja online saja bisa dibilang aman, lho. Para supplier sudah menandai produknya dengan tanggal sehingga kita bisa memastikan kesegarannya.\n\nSekarang mari kita mengolah resep cumi saus tiram simple ini! Hanya dengan membersihkan sejenak hingga tuntas dan memotong-motongnya, kamu sudah bisa langsung mempraktikkan resep cumi basah saus tiram ini untuk keluarga! Berapa lama waktu memasak cumi agar tidak alot? Setelah bercampur dengan bahan, cukup tumis sekitar satu menit di atas api sedang dan aduk-aduk hingga merata. Maka, tekstur cumi akan tetap terjaga kenyal dan empuk, pas banget dihidangkan untuk makan malam ataupun saat buka puasa.',
    category: 'Seafood',
    isNew: false,
    rate: 4.7,
    reviews: 103,
    time: 30,
    portion: 3,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '500_g cumi segar, siangi, iris melintang',
      '4_buah cabai merah besar, iris serong',
      '2_sdm Royco Saus Tiram',
      '2_sdm saus tomat',
      '1_sdm Bango Kecap Manis',
      '½_sdt garam',
      '1_buah bawang bombay, potong kotak',
      '½_sdm tepung maizena, larutkan dengan 2 sdm air',
      '3_sdm margarin',
      '6_siung bawang putih',
      '4_butir bawang merah',
      '2_cm jahe',
    ],
    procedures: [
      '1._Panaskan margarin, tumis bumbu halus hingga harum. Masukkan cumi, aduk hingga berubah warna.',
      '2._Masukkan cabai merah, Royco Saus Tiram, saus tomat, Bango Kecap Manis, dan garam, aduk rata.',
      '3._Tambahkan bawang bombay, aduk. Tuang larutan maizena, aduk hingga mengental dan matang. Angkat.',
      '4._Sajikan.',
    ],
  ),
  Food(
    name: 'Oseng Daging Sapi Pedas',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695126612/assets-smartchef/food/829918546_ueggo1.jpg',
    desc:
        'Sering bingung mengolah daging kurban? Cobain resep oseng daging sapi pedas ini, deh. Bisa diolah dari berbagai macam bagian sapi, misalnya has dalam, has luar, sengkel, sandung lamur, atau bagian iga.\n\nKalau menggunakan daging sapi yang cepat empuk misalnya has dalam dan has luar, daging bisa langsung ditumis. Tetapi jika menggunakan bagian daging yang butuh waktu untuk memasaknya, sebaiknya daging direbus terlebih dahulu hingga empuk. Untuk mengurangi aroma daging sapi yang kuat serta lemak berlebih, daging dapat direbus hingga mendidih, kemudian masak dengan air yang baru sampai empuk.\n\nYuk, buruan ke dapur dan siap-siap cobain resep oseng daging sapi ini! Ikuti juga akun Instagram Masak Apa Hari Ini untuk resep menarik lainnya.',
    category: 'Daging',
    isNew: true,
    rate: 4.7,
    reviews: 128,
    time: 90,
    portion: 6,
    chefName: 'Chef Arnold',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179133/assets-smartchef/chef/dQ6BDGovwq_zwpby6.jpg',
    chefAddress: 'Surabaya, Indonesia',
    ingredients: [
      '500_g daging sapi bagian sengkel atau sandung lamur',
      '2_l air',
      '4_lembar daun salam',
      '2_cm lengkuas, memarkan',
      '2_batang serai, memarkan',
      '2_sdm Bango Kecap Manis',
      '1_sdt Royco Kaldu Sapi',
      '50_g cabai rawit merah, potong kasar',
      '3_sdm minyak, untuk menumis',
      '10_buah cabai rawit merah',
      '8_buah cabai merah',
      '10_butir bawang merah',
      '3_siung bawang putih',
      '2_cm lengkuas',
      '2_cm jahe',
      '1_sdt garam',
    ],
    procedures: [
      '1._Rebus daging bersama 1 liter air hingga mendidih. Angkat dan buang airnya.',
      '2._Rebus kembali daging bersama sisa air. Masukkan daun salam dan lengkuas. Masak hingga daging empuk.',
      '3._Keluarkan daging dan sisihkan kaldunya. Potong-potong daging bentuk kotak 2 cm. Sisihkan.',
      '4._Panaskan minyak, tumis bumbu halus hingga harum. Masukkan daging, aduk rata.',
      '5._Tambahkan cabai rawit, Bango Kecap Manis, dan Royco Kaldu Sapi. Tambahkan 150 ml kaldu sisa merebus daging. Kecilkan api.',
      '6._Masak hingga meresap dan sebagian airnya menyusut.',
      '7._Masukkan buncis, aduk. Masak hingga buncis matang. Angkat dan sajikan.',
    ],
  ),
  Food(
    name: 'Teh Susu Mutiara',
    image:
        'https://res.cloudinary.com/fajardev/image/upload/v1695133699/assets-smartchef/food/9873238934_cmfceq.jpg',
    desc:
        'Jujurly, membuat teh susu itu gampang banget. Kamu hanya perlu menghangatkan susu dan tambah dengan seduhan teh. Tambahkan pemanis yang kamu suka dan jadi sudah yang namanya milk tea. Untuk resep ini, ada dua bahan yang menjadikan teh susu kamu makin sedap, yaitu kehadiran sagu mutiara yang dimasak juga bersama gula aren. Wah, rasanya bakal makin legit dan berkarakter!\n\nApakah bisa menggunakan alternatif lain selain sagu mutiara? Mengapa tidak? Kamu bisa menggunakan boba. Sebetulnya Masak Apa Hari Ini pernah berbagi rahasia membuat boba sendiri di rumah. Menarik untuk dilakukan karena bakal bikin siapapun yang menikmati racikan teh susu mutiara kamu jadi terkagum-kagum. Hanya memang, ada saja kalanya kamu ingin sesuatu yang lebih praktis. Maka, beruntunglah kita yang hidup di zaman keemasan milk tea seperti sekarang ini. Sekarang sudah tersedia boba instan, jadi tinggal kamu tambahkan saja ke dalam minumanmu.',
    category: 'Dessert',
    isNew: true,
    rate: 4.8,
    reviews: 281,
    time: 30,
    portion: 4,
    chefName: 'Chef Renatta',
    chefPhoto:
        'https://res.cloudinary.com/fajardev/image/upload/v1695179132/assets-smartchef/chef/5e16811892fc7_o2pbt5.jpg',
    chefAddress: 'Jakarta, Indonesia',
    ingredients: [
      '800_ml susu cair rendah lemak',
      '4_kantung SariWangi Teh Asli ',
      '100_g sagu mutiara atau boba',
      '100_g gula aren',
      '_Es batu',
    ],
    procedures: [
      '1._Masak boba sesuai aturan pemakaian air hingga hampir matang.',
      '2._Tambahkan gula aren, aduk perlahan hingga gula larut dan boba kenyal. Angkat. Sisihkan.',
      '3._Panaskan susu di atas api kecil. Angkat. Seduh SariWangi Teh Asli bersama susu panas selama 5 menit. Keluarkan teh. Sisihkan.',
      '4._Siapkan gelas saji, isi dengan es batu. Isi dengan boba. Tuang teh susu. Sajikan.',
    ],
  ),
];
