Insert into MON_CHK.VEI_DETTAGLIO_OGGETTI_INIZIATIVA values ('124456','MON_DATAMART','Tabella','FT_IND_MONTH_PMR',Current_date);
Insert into MON_CHK.VEI_DETTAGLIO_OGGETTI_INIZIATIVA values ('124456','MON_DATAMART','Tabella','FT_IND_WEEK_PMR',Current_date);
Insert into MON_CHK.VEI_DETTAGLIO_OGGETTI_INIZIATIVA values ('124456','MON_DATAMART','Tabella','PCL_KPI_CRUSCOTTO_PP_IND',Current_date);

CREATE COLUMN TABLE MON_DATAMART.FT_IND_MONTH_PMR (
	 CD_RITORNO						 VARCHAR(10),
	 WEEK_ISO 						 VARCHAR(6),
	 CODLINEA 						 VARCHAR(10),
	 CODPRODOTTO 					 VARCHAR(100),
	 CODSERVIZIO 					 VARCHAR(6),
	 CONSEGNATI_PMR					 INTEGER,
	 CONSEGNATI_PMR_IN_SLA			 INTEGER,
	 PRIMARY KEY (CD_RITORNO, WEEK_ISO, CODLINEA, CODPRODOTTO, CODSERVIZIO));
	 
CREATE COLUMN TABLE MON_DATAMART.FT_IND_WEEK_PMR (
	 CD_RITORNO						 VARCHAR(10),
	 WEEK_ISO 						 VARCHAR(6),
	 CODLINEA 						 VARCHAR(10),
	 CODPRODOTTO 					 VARCHAR(100),
	 CODSERVIZIO 					 VARCHAR(6),
	 CONSEGNATI_PMR					 INTEGER,
	 CONSEGNATI_PMR_IN_SLA			 INTEGER,
	 PRIMARY KEY (CD_RITORNO, WEEK_ISO, CODLINEA, CODPRODOTTO, CODSERVIZIO));
	 
CREATE COLUMN TABLE MON_DATAMART.PCL_KPI_CRUSCOTTO_PP_IND (
	DATA_AGG				TIMESTAMP,
	SETTIMANA_ISO			VARCHAR(6),
	MESE_ISO				VARCHAR(6),
	MACROPRODOTTO			VARCHAR(100),
	LOGISTICA				VARCHAR(100),
	KPI						VARCHAR(20),
	NUM						INTEGER,
	DEN						INTEGER,
PRIMARY KEY (SETTIMANA_ISO, MACROPRODOTTO, LOGISTICA, KPI)
);