-- MON_DATAMART.PCL_CONF_SEMAFORO 

INSERT INTO MON_DATAMART.PCL_CONF_SEMAFORO VALUES ('PCL_433_WW', CURRENT_TIMESTAMP);
INSERT INTO MON_DATAMART.PCL_CONF_SEMAFORO VALUES ('PCL_434_WW', CURRENT_TIMESTAMP);
INSERT INTO MON_DATAMART.PCL_CONF_SEMAFORO VALUES ('PCL_433_MM', CURRENT_TIMESTAMP);
INSERT INTO MON_DATAMART.PCL_CONF_SEMAFORO VALUES ('PCL_434_MM', CURRENT_TIMESTAMP);

-- MON_DATAMART.LOG_CARICAMENTO
  
INSERT INTO MON_DATAMART.LOG_CARICAMENTO 
select 
	"SERVIZIO",
	"NOME_JOB",
	'OK' as "ESITO_JOB",
	'107' as "CODICE_DM",
	'Ritono PMR Indescritta' as "NOME_DM",
	'033' as "PROGR_PROC",
	'INSERT_FT_IND_WEEK_PMR' as "NOME_PROCEDURA",
	"PAR_INPUT",
	"DESCR_PAR_INPUT",
	'OK' as "ESITO_PROC",
	'NO' as "RICALCOLO_PROC",
	null as "PAR_INPUT_RIC",
	"DESCR_PAR_INPUT_RIC",
	null as "NOTE_RICALCOLO",
	CURRENT_TIMESTAMP as "DATA_AGG"
 from "MON_DATAMART"."LOG_CARICAMENTO" WHERE PROGR_PROC = '012';
  
INSERT INTO MON_DATAMART.LOG_CARICAMENTO  
select 
	"SERVIZIO",
	"NOME_JOB",
	'OK' as "ESITO_JOB",
	'107' as "CODICE_DM",
	'Ritono PMR Indescritta' as "NOME_DM",
	'034' as "PROGR_PROC",
	'INSERT_FT_IND_MONTH_PMR' as "NOME_PROCEDURA",
	"PAR_INPUT",
	"DESCR_PAR_INPUT",
	'OK' as "ESITO_PROC",
	'NO' as "RICALCOLO_PROC",
	null as "PAR_INPUT_RIC",
	"DESCR_PAR_INPUT_RIC",
	null as "NOTE_RICALCOLO",
	CURRENT_TIMESTAMP as "DATA_AGG"
 from "MON_DATAMART"."LOG_CARICAMENTO" WHERE PROGR_PROC = '022';

-- MON_DATAMART.CONFIG_CARICAMENTO
  
INSERT INTO MON_DATAMART.CONFIG_CARICAMENTO
( SERVIZIO, PROGR_PROC, NOME_PROCEDURA, GIORNO_ESECUZIONE, 
  GIORNO_SETTIMANA, SETTIMANA_ESECUZIONE, SETTIMANA_MESE)
  VALUES
  ( 'IND', '033', 'INSERT_FT_IND_WEEK_PMR',4,'Giovedì',0,'Tutte');
  
INSERT INTO MON_DATAMART.CONFIG_CARICAMENTO
( SERVIZIO, PROGR_PROC, NOME_PROCEDURA, GIORNO_ESECUZIONE, 
  GIORNO_SETTIMANA, SETTIMANA_ESECUZIONE, SETTIMANA_MESE)
  VALUES
  ( 'IND', '034', 'INSERT_FT_IND_MONTH_PMR',4,'Giovedì',2,'Seconda');

-- MON_DATAMART.TABLEAU_CONFIG_FLUSSO

INSERT INTO MON_DATAMART.TABLEAU_CONFIG_FLUSSO 	 
select 
'PCL_433' 			AS "FLUSSO",
CURRENT_DATE 		AS "DATA_CREAZIONE",
'INSERT_PCL433_WW'  AS "NOME_PROCEDURA",
"PARA_INPUT",
"FREQUENZA",
"GIORNO",
"GIORNO_DATA_INIZIO",
"GIORNO_DATA_FINE",
CURRENT_DATE AS "DATA_AGG",
"BACKWEEK",
"FLAG_ATTIVAZIONE",
"GIORNO_EXEC_INT",
"SETTIMANA_EXEC_INT",
"N_WEEK" 
FROM MON_DATAMART.TABLEAU_CONFIG_FLUSSO  WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_WW';

INSERT INTO MON_DATAMART.TABLEAU_CONFIG_FLUSSO 	 
select 
'PCL_434' 			AS "FLUSSO",
CURRENT_DATE 		AS "DATA_CREAZIONE",
'INSERT_PCL434_WW'  AS "NOME_PROCEDURA",
"PARA_INPUT",
"FREQUENZA",
"GIORNO",
"GIORNO_DATA_INIZIO",
"GIORNO_DATA_FINE",
CURRENT_DATE AS "DATA_AGG",
"BACKWEEK",
"FLAG_ATTIVAZIONE",
"GIORNO_EXEC_INT",
"SETTIMANA_EXEC_INT",
"N_WEEK" 
FROM MON_DATAMART.TABLEAU_CONFIG_FLUSSO  WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_WW';

INSERT INTO MON_DATAMART.TABLEAU_CONFIG_FLUSSO 	 
select 
'PCL_433' 			AS "FLUSSO",
CURRENT_DATE 		AS "DATA_CREAZIONE",
'INSERT_PCL433_MM'  AS "NOME_PROCEDURA",
"PARA_INPUT",
"FREQUENZA",
"GIORNO",
"GIORNO_DATA_INIZIO",
"GIORNO_DATA_FINE",
CURRENT_DATE AS "DATA_AGG",
"BACKWEEK",
"FLAG_ATTIVAZIONE",
"GIORNO_EXEC_INT",
"SETTIMANA_EXEC_INT",
"N_WEEK" 
FROM MON_DATAMART.TABLEAU_CONFIG_FLUSSO  WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_MM';

INSERT INTO MON_DATAMART.TABLEAU_CONFIG_FLUSSO 	 
select 
'PCL_434' 			AS "FLUSSO",
CURRENT_DATE 		AS "DATA_CREAZIONE",
'INSERT_PCL434_MM'  AS "NOME_PROCEDURA",
"PARA_INPUT",
"FREQUENZA",
"GIORNO",
"GIORNO_DATA_INIZIO",
"GIORNO_DATA_FINE",
CURRENT_DATE AS "DATA_AGG",
"BACKWEEK",
"FLAG_ATTIVAZIONE",
"GIORNO_EXEC_INT",
"SETTIMANA_EXEC_INT",
"N_WEEK" 
FROM MON_DATAMART.TABLEAU_CONFIG_FLUSSO  WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_MM';

-- MON_DATAMART.TABLEAU_ESECUZIONE_FLUSSO

INSERT INTO MON_DATAMART.TABLEAU_ESECUZIONE_FLUSSO			 
 select 
'PCL_433' AS "FLUSSO",
"DATA_ESECUZIONE",
'INSERT_PCL433_WW' AS "NOME_PROCEDURA",
"PARA_INPUT",
"ESITO",
CURRENT_TIMESTAMP "DATA_AGG",
"FREQUENZA",
"TIPO_ESECUZIONE"
 from "MON_DATAMART"."TABLEAU_ESECUZIONE_FLUSSO"
WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_WW'AND ESITO = 0 AND TIPO_ESECUZIONE = 'S';

INSERT INTO MON_DATAMART.TABLEAU_ESECUZIONE_FLUSSO			 
 select 
'PCL_434' AS "FLUSSO",
"DATA_ESECUZIONE",
'INSERT_PCL434_WW' AS "NOME_PROCEDURA",
"PARA_INPUT",
"ESITO",
CURRENT_TIMESTAMP "DATA_AGG",
"FREQUENZA",
"TIPO_ESECUZIONE"
 from "MON_DATAMART"."TABLEAU_ESECUZIONE_FLUSSO"
WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_WW'AND ESITO = 0 AND TIPO_ESECUZIONE = 'S';
			 
INSERT INTO MON_DATAMART.TABLEAU_ESECUZIONE_FLUSSO			 
 select 
'PCL_433' AS "FLUSSO",
"DATA_ESECUZIONE",
'INSERT_PCL433_MM' AS "NOME_PROCEDURA",
"PARA_INPUT",
"ESITO",
CURRENT_TIMESTAMP "DATA_AGG",
"FREQUENZA",
"TIPO_ESECUZIONE"
 from "MON_DATAMART"."TABLEAU_ESECUZIONE_FLUSSO"
WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_MM'AND ESITO = 0 AND TIPO_ESECUZIONE = 'S';

INSERT INTO MON_DATAMART.TABLEAU_ESECUZIONE_FLUSSO			 
 select 
'PCL_434' AS "FLUSSO",
"DATA_ESECUZIONE",
'INSERT_PCL434_MM' AS "NOME_PROCEDURA",
"PARA_INPUT",
"ESITO",
CURRENT_TIMESTAMP "DATA_AGG",
"FREQUENZA",
"TIPO_ESECUZIONE"
 from "MON_DATAMART"."TABLEAU_ESECUZIONE_FLUSSO"
WHERE FLUSSO = 'PCL_400' AND NOME_PROCEDURA = 'INSERT_PCL400_MM'AND ESITO = 0 AND TIPO_ESECUZIONE = 'S';	

-- MON_DATAMART.CONFIG_KPI			

INSERT INTO MON_DATAMART.CONFIG_KPI VALUES ('PCL_433_WW','% Tracciatura al Civico - Posta 1 PRO','PCL_433_WW');

INSERT INTO MON_DATAMART.CONFIG_KPI VALUES ('PCL_434_WW','% SLA - Resi indescritta','PCL_434_WW');

INSERT INTO MON_DATAMART.CONFIG_KPI VALUES ('PCL_433_MM','% Tracciatura al Civico - Posta 1 PRO','PCL_433_MM');

INSERT INTO MON_DATAMART.CONFIG_KPI VALUES ('PCL_434_MM','% SLA - Resi indescritta','PCL_434_MM');

-- PCL_433

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_433', 'ACCETTAZIONE', 'Posta 1 Pro','PRI','','C-',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_433', 'ACCETTAZIONE', 'Posta 1 Pro','PRI','','CT',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_433', 'ACCETTAZIONE', 'Posta 1 Pro','PRI','','Q-',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_433', 'ACCETTAZIONE', 'Posta 1 Pro','PRI','','QR',NULL);
	
-- PCL_434

-- Billing Mail

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Billing Mail','BIL','','CT',NULL);
	
-- Posta Massiva

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Massiva','MS','','TR',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Massiva','MS','','CT',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Massiva','MS','','TT',NULL);
	
-- Posta Contest

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Contest','BM','BMQ','CT',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Contest','BM','BMS','CT',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Contest','BM','BMQ','CT,PID',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Contest','BM','BMS','CT,PID',NULL);

-- Posta Time

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Time','PT','','CT',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Time','PT','','TT',NULL);
	
-- Posta Target	
	
-- PGCFP

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGCFP','C-',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGCFP','TR',NULL);
	
-- PGBFP
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGBFP','C-',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGBFP','TR',NULL);
	
-- PGWFP

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGWFP','C-',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGWFP','TR',NULL);
	
-- PGGFP

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGGFP','C-',NULL);
	
INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGGFP','TR',NULL);
	
-- PGCFM

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGCFM','C-',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGCFM','TR',NULL);
	
-- PGMFM

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGMFM','C-',NULL);

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta Target','PTA','PGMFM','TR',NULL);
	
-- Posta 1 Pro

INSERT INTO MON_DATAMART.IND_PCL_ANAG_MACROPRODOTTO
			(CODICE_FLUSSO, DM, MACROPRODOTTO, CODLINEA, CODPRODOTTO, CODSERVIZIO, CANALEACCETTAZIONE)
	VALUES ( 'PCL_434', 'Ritono PMR Indescritta', 'Posta 1 Pro','PRI','','QR',NULL);
	
--1

/* INSTALL CONFIG */

-- PCL_300, PCL_300_NXV  Pacchi notificati in SLA - veloci
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Crono Express' 		  			   , 'PKX'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Crono Express' 		  			   , 'CKX'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'Crono Express (con C/A)' 			  							, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Poste Delivery Business Express'     , 'PBE'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'PosteDelivery Business Express'									, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Poste Delivery Business Express'     , 'CBE'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'PosteDelivery Business Express Contrassegno'  					, null  , null ); 
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Poste Delivery Business Express'     , 'MBE'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'PosteDelivery Business Multicollo Express'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'Poste Delivery Business Express'     , 'MBEF'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'PosteDelivery Business Multicollo Express (STICKER MULTICOLLO)'	, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'SESP'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'SESPF'   , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'XLA'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'XLAF'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'XLP'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE STANDARD'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300', 'ESPRESSO SDA'     				   , 'XLPF'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'Crono Express' 		  		   , 'PKX'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'Crono Express' 		  		   , 'CKX'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'Crono Express (con C/A)' 			  							, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'SESP'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'SESPF'   , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'XLA'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'XLAF'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'XLP'     , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE STANDARD'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_300_NXV', 'ESPRESSO SDA'     			   , 'XLPF'    , '9999-12-31' , '1900-01-01' , 'Oggetti Notificati in SLA - veloci' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

UPDATE "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" 
	SET "DATA_FINE_VALIDITA" = CURRENT_DATE
	WHERE "CLASSE" IN ( 'PCL_301',  'PCL_301_NXV' )
	  AND "MACRO_PRODOTTO" = 'Postedelivery standard'
	  AND "DATA_FINE_VALIDITA" = '9999-12-31'
;

-- PCL_302, PCL_302_NXV  % FTDS - Consegna al I tentativo
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Crono Express' 		  			   , 'PKX'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Crono Express' 		  			   , 'CKX'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'Crono Express (con C/A)' 			  							, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Poste Delivery Business Express'     , 'PBE'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'PosteDelivery Business Express'									, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Poste Delivery Business Express'     , 'CBE'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'PosteDelivery Business Express Contrassegno'  					, null  , null ); 
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Poste Delivery Business Express'     , 'MBE'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'PosteDelivery Business Multicollo Express'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'Poste Delivery Business Express'     , 'MBEF'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'PosteDelivery Business Multicollo Express (STICKER MULTICOLLO)'	, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'SESP'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'SESPF'   , '9999-12-31' , '1900-01-01' , '% FTDS' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'XLA'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'XLAF'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'XLP'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE STANDARD'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302', 'ESPRESSO SDA'     				   , 'XLPF'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'Crono Express' 		  		   , 'PKX'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'Crono Express' 		  		   , 'CKX'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'Crono Express (con C/A)' 			  							, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'SESP'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'SESPF'   , '9999-12-31' , '1900-01-01' , '% FTDS' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'XLA'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'XLAF'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'XLP'     , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE STANDARD'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_302_NXV', 'ESPRESSO SDA'     			   , 'XLPF'    , '9999-12-31' , '1900-01-01' , '% FTDS' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

UPDATE "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" 
	SET "DATA_FINE_VALIDITA" = CURRENT_DATE
	WHERE "CLASSE" IN ( 'PCL_302',  'PCL_302_NXV' )
	  AND "MACRO_PRODOTTO" = 'Postedelivery standard'
	  AND "DATA_FINE_VALIDITA" = '9999-12-31'
;

-- PCL_303, PCL_303_NXV  % TDS - Consegna al I+II tentativo
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Crono Express' 		  			   , 'PKX'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Crono Express' 		  			   , 'CKX'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'Crono Express (con C/A)' 			  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Poste Delivery Business Express'     , 'PBE'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'PosteDelivery Business Express'									, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Poste Delivery Business Express'     , 'CBE'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'PosteDelivery Business Express Contrassegno'  					, null  , null ); 
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Poste Delivery Business Express'     , 'MBE'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'PosteDelivery Business Multicollo Express'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'Poste Delivery Business Express'     , 'MBEF'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'PosteDelivery Business Multicollo Express (STICKER MULTICOLLO)'	, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'SESP'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'SESPF'   , '9999-12-31' , '1900-01-01' , '% TDS' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'XLA'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'XLAF'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'XLP'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE STANDARD'												, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303', 'ESPRESSO SDA'     				   , 'XLPF'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'Crono Express' 		  		   , 'PKX'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'Crono Express' 					  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'Crono Express' 		  		   , 'CKX'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'Crono Express (con C/A)' 			  								, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'SESP'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'SDA SERVIZIO ESPRESSO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'SESPF'   , '9999-12-31' , '1900-01-01' , '% TDS' , 'SDA SERVIZIO ESPRESSO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'XLA'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE ASSICURATO'											, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'XLAF'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE ASSICURATO (STICKER MULTICOLLO)'						, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'XLP'     , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE STANDARD'												, null  , null );
INSERT INTO "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" VALUES( 'PCL_303_NXV', 'ESPRESSO SDA'     			   , 'XLPF'    , '9999-12-31' , '1900-01-01' , '% TDS' , 'EXTRA LARGE STANDARD (STICKER MULTICOLLO)'						, null  , null );

UPDATE "MON_DATAMART"."TABLEAU_ANAG_PRODOTTI_PACCHI" 
	SET "DATA_FINE_VALIDITA" = CURRENT_DATE
	WHERE "CLASSE" IN ( 'PCL_303',  'PCL_303_NXV' )
	  AND "MACRO_PRODOTTO" = 'Postedelivery standard'
	  AND "DATA_FINE_VALIDITA" = '9999-12-31'
;


--2

/* INSTALL CONFIG */

-- PCL_200  --> Inesitate Posta Registrata ( PE2E ) 
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 1,  'RACCOMANDATA 1'	 , 'RC' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 1,  'RACCOMANDATA 1'	 , 'RP' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 1,  'RACCOMANDATA 1'	 , 'RV' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 2,  'RACCOMANDATA 4'	 , 'R'  , 'SI', 'RACCOMANDATA 4 (R)'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 2,  'RACCOMANDATA 4'	 , 'RAG', 'SI', 'RACCOMANDATA 4 (RAG)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 2,  'RACCOMANDATA 4'	 , 'ROL', 'SI', 'RACCOMANDATA 4 (ROL)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 3,  'ASSICURATA'		 , 'ACV', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 3,  'ASSICURATA'		 , 'AVL', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 3,  'ASSICURATA'		 , 'AVO', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 4,  'ATTI GIUDIZIARI'	 , 'AG' , 'SI', 'ATTI GIUDIZIARI'			 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 5,  'RACCOMANDATA MARKET', 'RK' , 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 5,  'RACCOMANDATA MARKET', 'RK2', 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 5,  'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 5,  'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 5,  'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 6,  'ADVICE MAIL'		 , 'R'  , 'NO', 'ADVICE MAIL'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 9,  'AG MARKET'			 , 'AGM', 'NO', 'AG MARKET'					 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 9,  'AG MARKET'			 , 'AGE', 'NO', 'AG MARKET'		    		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 7,  'RACC ESTERO INBOUND', 'EE' , 'NO', 'POSTEMINIBOXTRACK' 		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200', 16, 'INBOUND EXPRESS'	 , 'EXI', 'NO', 'INBOUND EXPRESS'			 , '1900-01-01', '9999-12-31' ) ;

-- PCL_200_NXV -> Inesitate Posta Registrata ( PE2E ) 
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 1,  'RACCOMANDATA 1'	 , 'RC' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 1,  'RACCOMANDATA 1'	 , 'RP' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 1,  'RACCOMANDATA 1'	 , 'RV' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 2,  'RACCOMANDATA 4'	 , 'R'  , 'SI', 'RACCOMANDATA 4 (R)'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 2,  'RACCOMANDATA 4'	 , 'RAG', 'SI', 'RACCOMANDATA 4 (RAG)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 2,  'RACCOMANDATA 4'	 , 'ROL', 'SI', 'RACCOMANDATA 4 (ROL)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 3,  'ASSICURATA'		 , 'ACV', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 3,  'ASSICURATA'		 , 'AVL', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 3,  'ASSICURATA'		 , 'AVO', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 4,  'ATTI GIUDIZIARI'	 , 'AG' , 'SI', 'ATTI GIUDIZIARI'			 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 5,  'RACCOMANDATA MARKET', 'RK' , 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 5,  'RACCOMANDATA MARKET', 'RK2', 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 5,  'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 5,  'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 5,  'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 6,  'ADVICE MAIL'		 , 'R'  , 'NO', 'ADVICE MAIL'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 9,  'AG MARKET'			 , 'AGM', 'NO', 'AG MARKET'					 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 9,  'AG MARKET'			 , 'AGE', 'NO', 'AG MARKET'		    		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 7, 'RACC ESTERO INBOUND' , 'EE' , 'NO', 'POSTEMINIBOXTRACK' 		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_200_NXV', 16, 'INBOUND EXPRESS'	 , 'EXI', 'NO', 'INBOUND EXPRESS'			 , '1900-01-01', '9999-12-31' ) ;

-- PCL_215  --> Inesitate Posta Registrata ( PE2E ) 
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 1,  'RACCOMANDATA 1'	 , 'RC' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 1,  'RACCOMANDATA 1'	 , 'RP' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 1,  'RACCOMANDATA 1'	 , 'RV' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 2,  'RACCOMANDATA 4'	 , 'R'  , 'SI', 'RACCOMANDATA 4 (R)'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 2,  'RACCOMANDATA 4'	 , 'RAG', 'SI', 'RACCOMANDATA 4 (RAG)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 2,  'RACCOMANDATA 4'	 , 'ROL', 'SI', 'RACCOMANDATA 4 (ROL)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 3,  'ASSICURATA'		 , 'ACV', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 3,  'ASSICURATA'		 , 'AVL', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 3,  'ASSICURATA'		 , 'AVO', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 4,  'ATTI GIUDIZIARI'	 , 'AG' , 'SI', 'ATTI GIUDIZIARI'			 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 5,  'RACCOMANDATA MARKET', 'RK' , 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 5,  'RACCOMANDATA MARKET', 'RK2', 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 5,  'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 5,  'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 5,  'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215', 6,  'ADVICE MAIL'		 , 'R'  , 'NO', 'ADVICE MAIL'				 , '1900-01-01', '9999-12-31' ) ;

-- PCL_215_NXV -> Inesitate Posta Registrata ( PE2E ) 
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 1,  'RACCOMANDATA 1'	 , 'RC' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 1,  'RACCOMANDATA 1'	 , 'RP' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 1,  'RACCOMANDATA 1'	 , 'RV' , 'NO', 'RACCOMANDATA 1'		     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 2,  'RACCOMANDATA 4'	 , 'R'  , 'SI', 'RACCOMANDATA 4 (R)'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 2,  'RACCOMANDATA 4'	 , 'RAG', 'SI', 'RACCOMANDATA 4 (RAG)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 2,  'RACCOMANDATA 4'	 , 'ROL', 'SI', 'RACCOMANDATA 4 (ROL)'	     , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 3,  'ASSICURATA'		 , 'ACV', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 3,  'ASSICURATA'		 , 'AVL', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 3,  'ASSICURATA'		 , 'AVO', 'SI', 'ASSICURATA'				 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 4,  'ATTI GIUDIZIARI'	 , 'AG' , 'SI', 'ATTI GIUDIZIARI'			 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 5,  'RACCOMANDATA MARKET', 'RK' , 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 5,  'RACCOMANDATA MARKET', 'RK2', 'NO', 'RACCOMANDATA MARKET'        , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 5,  'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 5,  'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		 , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 5,  'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_215_NXV', 6,  'ADVICE MAIL'		 , 'R'  , 'NO', 'ADVICE MAIL'				 , '1900-01-01', '9999-12-31' ) ;

-- PCL_221  -> Lenti Persona I SLA ( PE2E )
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_221', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_221', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_221', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

-- PCL_206  --> Lenti Persona I SLA ( PE2E )
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

-- PCL_206_NXV --> Lenti Persona I SLA ( PE2E )
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206_NXV', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206_NXV', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_206_NXV', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

-- PCL_209   --> Lenti Persona III SLA ( PE2E )														  
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_209', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_209', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_209', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

-- PCL_212   --> Lenti Persona II SLA ( PE2E )															  
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_212', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_212', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_212', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

-- PCL_232   --> Causa Forza Maggiore ( PE2E )
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_232', 9, 'AG MARKET', 'AGM', 'NO', 'AG MARKET', '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_232', 9, 'AG MARKET', 'AGE', 'NO', 'AG MARKET', '1900-01-01', '9999-12-31' ) ;
															  
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_232', 5, 'RACCOMANDATA MARKET', 'RKE', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_232', 5, 'RACCOMANDATA MARKET', 'RKD', 'NO', 'RACCOMANDATA MARKET'		, '1900-01-01', '9999-12-31' ) ;
INSERT INTO "MON_ANAG"."PE2E_PCL_ANAG_MACROPRODOTTO" VALUES( 'PCL_232', 5, 'RACCOMANDATA MARKET', 'RKX', 'NO', 'RACCOMANDATA MARKET NEXIVE' , '1900-01-01', '9999-12-31' ) ;

--3

/* INSTALL CONFIG */

-- PCL_203   --> % Sequenza tracce anomale (cons. dopo reso) ( PDES )
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGM', 'NO', null, null, 'NO', 'PCL_203' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGE', 'NO', null, null, 'NO', 'PCL_203' ) ;

INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKE', 'NO', null, null, 'NO', 'PCL_203' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKD', 'NO', null, null, 'NO', 'PCL_203' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKX', 'NO', null, null, 'NO', 'PCL_203' ) ;

-- PCL_204   --> % Sequenza tracce anomale (cons. dopo ines.) ( PDES )
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGM', 'NO', null, null, 'NO', 'PCL_204' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGE', 'NO', null, null, 'NO', 'PCL_204' ) ;

INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKE', 'NO', null, null, 'NO', 'PCL_204' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKD', 'NO', null, null, 'NO', 'PCL_204' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKX', 'NO', null, null, 'NO', 'PCL_204' ) ;

-- PCL_227   --> Inesitate Distanza ( PDES )
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGM', 'NO', null, null, 'NO', 'PCL_227' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 12, 'AGE/AGM', 'AGE', 'NO', null, null, 'NO', 'PCL_227' ) ;

INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKE', 'NO', null, null, 'NO', 'PCL_227' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKD', 'NO', null, null, 'NO', 'PCL_227' ) ;
INSERT INTO "MON_ANAG"."PCL_ANAG_MACROPRODOTTO" VALUES( 5, 'Raccomandate Market', 'RKX', 'NO', null, null, 'NO', 'PCL_227' ) ;